### ISSUE TITLE
Animation not downloading 

### ISSUE THREAD

**Issue by Dark128-sys** [TheLogicMaster/SDH-AnimationChanger#62]
When selecting Download it works and shows Downloaded, but under "Installed" it still show (0).How can i fix it?

**Comment by breakstate** [comment]
I'm having the same issue on SteamOS V3.6.19. 

Tried the following without success:
- changing permissions for the animation directories in desktop mode (to allow reading and writing for everyone)
- reinstalling the plugin multiple times
- forcing ipv4
- restarting deck

**Comment by nargual** [comment]
I'm having the same problem.

**Comment by TolgaYigit** [comment]
As of today, having the same problem with brand new steam deck.

**Comment by TheLogicMaster** [comment]
Is there any information in the plugin log file as far as what is happening?

**Comment by CherryZeff** [comment]
Im having the same issue, here's the file log content

```
[2025-02-11 14:00:04,418][INFO]: Migrating
[2025-02-11 14:00:04,419][INFO]: Initializing...
[2025-02-11 14:00:09,847][INFO]: Initialized
[2025-02-11 14:01:09,237][ERROR]: Invalid download request status: 502
[2025-02-11 14:01:09,238][ERROR]: Failed to download animation
Traceback (most recent call last):
  File "/home/deck/homebrew/plugins/SDH-AnimationChanger/main.py", line 393, in downloadAnimation
    raise_and_log(f'Invalid download request status: {response.status}')
  File "/home/deck/homebrew/plugins/SDH-AnimationChanger/main.py", line 138, in raise_and_log
    raise Exception(msg)
Exception: Invalid download request status: 502
[2025-02-11 14:04:48,623][ERROR]: Invalid download request status: 504
[2025-02-11 14:04:48,623][ERROR]: Failed to download animation
Traceback (most recent call last):
  File "/home/deck/homebrew/plugins/SDH-AnimationChanger/main.py", line 393, in downloadAnimation
    raise_and_log(f'Invalid download request status: {response.status}')
  File "/home/deck/homebrew/plugins/SDH-AnimationChanger/main.py", line 138, in raise_and_log
    raise Exception(msg)
Exception: Invalid download request status: 504
```
For more info: I accidentally uninstalled Decky when uninstalling EmuDeck and had to reinstall it. So maybe that had to do something with this issue

Last edit: I was able to redownload animation, just had to restart the deck, don't know what happened tho.
